#
# Replace "???" values as required for your environment
#
export QBO_APIBASE="https://${QBO_SANDBOX}quickbooks.api.intuit.com/v3"
export QBO_REALMID="???"
export QBO_FORMAT=json
export QBO_SCOPE=com.intuit.quickbooks.accounting
#
export OAUTH2_CONNECT_SERVER="https://appcenter.intuit.com/connect/oauth2"
export OAUTH2_TOKEN_SERVER="https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer"
export OAUTH2_CALLBACK="https://???/callback.cgi"
export OAUTH2_CLIENT="???"
export OAUTH2_SECRET="???"
export OAUTH2_REFRESH_TOKEN="???"
export OAUTH2_ACCESS_TOKEN="???"
